services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    extra_hosts:
      - "mfaoussi.42.fr:127.0.0.1"
    volumes:
      - /home/mfaoussi/data/wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - /home/mfaoussi/data/wordpress:/var/www/html
    networks:
      - inception


networks:
  inception:
    driver: bridge
